### ISSUE TITLE
Install triggert jeden Run apt update

### ISSUE THREAD

**Issue by nce** [vision-it/vision-icinga2#1]
Sollte angepasst werden, sodass nicht jeden run ein unnoetiges update getriggert wird.

[Source](https://github.com/vision-it/vision-icinga2/blob/production/manifests/common/install.pp#L37)

Fix?

``` puppet
 onlyif => "/bin/bash -c 'exit $(( $(( $(date +%s) - $(stat -c %Y /var/lib/apt/lists/$( ls /var/lib/apt/lists/ -tr1|tail -1 )) )) <= 604800 ))'"
```

Sollte `update` nur ausfuehren wenn die repos aelter als eine Woche sind.

**Comment by jacksgt** [comment]
Dürfte ja gefixt sein:
https://github.com/vision-it/vision-icinga2/blob/production/manifests/common/install.pp#L38
